### ISSUE TITLE
Change readme.md to .rst

### ISSUE THREAD

**Issue by ArnaudGaudry** [mandelbrot-project/memo#22]
Change Readme from .md to .rst for pypi compatibility.

**Comment by ArnaudGaudry** [comment]
Small question @florian-huber! I changed the Readme to .rst, to make changes effective on pypi I should just add "long_description_content_type='text/x-rst'" to setup.py and then upload it as before to pypi?

**Comment by florian-huber** [comment]
Yes, adding that to the setup.py should do the trick.
If you run into trouble with uploading to pypi again, then I wouldn't bother too much. We can soon release a 0.1.1 whenever we add some minor changes.

**Comment by ArnaudGaudry** [comment]
Sounds good to me, i’ll change setup.py then and wait for the next release to apply changes.
