### ISSUE TITLE
[enhancement] add possibility to filter words present only in > or < than x% of the samples

### ISSUE THREAD

**Issue by Adafede** [mandelbrot-project/memo#25]
add arguments to [`filter_table`](https://github.com/mandelbrot-project/memo/blob/f2672e00f06483627d9ef0c0c412423cde060b2a/memo_ms/classes.py#L11)

**Comment by ArnaudGaudry** [comment]
Good idea! See https://github.com/mandelbrot-project/memo/releases/tag/v0.1.4 ;)
